FROM node:latest

WORKDIR /app

COPY package.json .

COPY .npmrc .npmrc

RUN npm install

RUN rm -f .npmrc

COPY . .

EXPOSE 3002

CMD [ "npm", "run", "api" ]
# WORKDIR /app
# RUN apt-get update
# COPY index.html package.json package-lock.json .
# COPY .npmrc .npmrc
# RUN npm install
# RUN rm -f .npmrc
# COPY src/ .
# EXPOSE 3000 3001 3002
# CMD [ "npm", "start"]