# fly.toml app configuration file generated for trill-pics on 2024-03-31T11:14:29+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trill-pics'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
