[dev]
  command = "npm run dev"
  framework = "vite"
  targetPort = 3000
[build]
  command = "npm run build"
  publish = "dist"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", '@remotion/compositor-*']
  included_files = ["./downloads/**/*"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:x"
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''