[build]
  command = "npm run build"
  publish = "dist"
[functions]
  external_node_modules = ["express", "@remotion/bundler", "@remotion/renderer"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/trpc/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
