import { Rule } from "unocss";
import {
  GRADIENT_BLUE_PINK_YELLOW,
  GRADIENT_TEXT_COMMON,
  GRADIENT_TEAL_YELLOW_PINK,
  GRADIENT_BORDER_COMMON,
  RADIAL_BLUE_PINK_YELLOW,
  RADIAL_TEAL_YELLOW_PINK,
  GRADIENT_NET_COMMON,
  GRADIENT_NET_DARK,
  GRADIENT_NET_LIGHT,
} from "../../app/color/gradient";

export const GRADIENTS: Rule[] = [
  [
    "_dark-gradient-net",
    {
      ...GRADIENT_NET_DARK,
      ...GRADIENT_NET_COMMON,
    },
  ],
  [
    "_light-gradient-net",
    {
      ...GRADIENT_NET_LIGHT,
      ...GRADIENT_NET_COMMON,
    },
  ],
  [
    "_dark-gradient-text",
    {
      "background-image":
        GRADIENT_BLUE_PINK_YELLOW,
      ...GRADIENT_TEXT_COMMON,
    },
  ],
  [
    "_light-gradient-text",
    {
      "background-image":
        GRADIENT_TEAL_YELLOW_PINK,
      ...GRADIENT_TEXT_COMMON,
    },
  ],
  [
    "_dark-gradient-border",
    {
      "border-image": `${GRADIENT_BLUE_PINK_YELLOW} 20`,
      ...GRADIENT_BORDER_COMMON,
    },
  ],
  [
    "_light-gradient-border",
    {
      "border-image": `${GRADIENT_TEAL_YELLOW_PINK} 20`,
      ...GRADIENT_BORDER_COMMON,
    },
  ],
  [
    "_dark-radial-gradient",
    {
      "background-image":
        RADIAL_BLUE_PINK_YELLOW,
    },
  ],
  [
    "_light-radial-gradient",
    {
      "background-image":
        RADIAL_TEAL_YELLOW_PINK,
    },
  ],
  [
    "_dark-linear-gradient",
    {
      "background-image":
        GRADIENT_BLUE_PINK_YELLOW,
    },
  ],
  [
    "_light-linear-gradient",
    {
      "background-image":
        GRADIENT_TEAL_YELLOW_PINK,
    },
  ],
];
