[build]
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''


  # Configuration for a plugin published to npm
[[plugins]]
package = "netlify-plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse.html"